# Generated by Django 3.1.6 on 2021-06-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('AN', 'Any level'), ('BE', 'Beginner'), ('IN', 'Intermediate'), ('AD', 'Advanced')], default='AN', max_length=2)),
                ('type', models.CharField(choices=[('PO', 'Podcast'), ('BO', 'Book'), ('AB', 'Audiobook'), ('BL', 'Blog'), ('AR', 'Article'), ('CO', 'Course'), ('VI', 'Video'), ('TO', 'Tool'), ('OT', 'Other')], default='OT', max_length=2)),
                ('url', models.URLField(max_length=300)),
                ('description', models.TextField(max_length=500)),
                ('tagline', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='link',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='links', to='api.Tag'),
        ),
    ]
