# Generated by Django 3.1.6 on 2021-07-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210609_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('form_name', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=5000)),
            ],
        ),
    ]
