# Generated by Django 3.1.6 on 2021-08-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_formsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('PO', 'Podcast'), ('BO', 'Book'), ('AB', 'Audiobook'), ('BL', 'Blog'), ('AR', 'Article'), ('CO', 'Course'), ('VI', 'Video'), ('TO', 'Tool'), ('OT', 'Other'), ('DO', 'Documentation'), ('FO', 'Forum')], default='OT', max_length=2),
        ),
    ]
